# Use root/example as user/password credentials

services:

  db:
    image: 'mysql:lts'
    restart: 'always'
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=admin'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_DATABASE=docker'
    # (this is just an example, not intended to be a production configuration)
